"""tmachine table

Revision ID: 7bcd1a9ab895
Revises: 
Create Date: 2018-05-29 13:53:58.386021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcd1a9ab895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmachine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definicia', sa.String(length=100), nullable=True),
    sa.Column('tm_d_n_x', sa.String(length=16), nullable=True),
    sa.Column('states', sa.String(length=200), nullable=True),
    sa.Column('input_symbols', sa.String(length=100), nullable=True),
    sa.Column('tape_symbols', sa.String(length=200), nullable=True),
    sa.Column('left_end', sa.String(length=16), nullable=True),
    sa.Column('transitions', sa.String(length=1000), nullable=True),
    sa.Column('initial_state', sa.String(length=16), nullable=True),
    sa.Column('blank_symbol', sa.String(length=16), nullable=True),
    sa.Column('reject_state', sa.String(length=16), nullable=True),
    sa.Column('final_states', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmachine_blank_symbol'), 'tmachine', ['blank_symbol'], unique=False)
    op.create_index(op.f('ix_tmachine_definicia'), 'tmachine', ['definicia'], unique=True)
    op.create_index(op.f('ix_tmachine_final_states'), 'tmachine', ['final_states'], unique=False)
    op.create_index(op.f('ix_tmachine_initial_state'), 'tmachine', ['initial_state'], unique=False)
    op.create_index(op.f('ix_tmachine_input_symbols'), 'tmachine', ['input_symbols'], unique=False)
    op.create_index(op.f('ix_tmachine_left_end'), 'tmachine', ['left_end'], unique=False)
    op.create_index(op.f('ix_tmachine_reject_state'), 'tmachine', ['reject_state'], unique=False)
    op.create_index(op.f('ix_tmachine_states'), 'tmachine', ['states'], unique=False)
    op.create_index(op.f('ix_tmachine_tape_symbols'), 'tmachine', ['tape_symbols'], unique=False)
    op.create_index(op.f('ix_tmachine_tm_d_n_x'), 'tmachine', ['tm_d_n_x'], unique=False)
    op.create_index(op.f('ix_tmachine_transitions'), 'tmachine', ['transitions'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tmachine_transitions'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_tm_d_n_x'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_tape_symbols'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_states'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_reject_state'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_left_end'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_input_symbols'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_initial_state'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_final_states'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_definicia'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_blank_symbol'), table_name='tmachine')
    op.drop_table('tmachine')
    # ### end Alembic commands ###
